name: Continuous Integration

on:
  pull_request:
    branches: [ develop, feature/* ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: run install, build and test
        run: |
          npm install
          npm run build --if-present
          npm run test

