name: Continuous Integration

on:
  pull_request:
    branches: [ develop, feature/* ]
  push:
    branches: [ develop, feature/* ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: run install, build and test
        run: |
          npm install
          npm run build --if-present
          npm run test

      - name: Auto pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref }}
          destination_branch: develop
          pr_title: ${{ github.ref }}
          pr_body: |
            ${{ github.ref }}
            ${{ github.event.head_commit.message }}
            ${{ github.event.pull_request.html_url }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

